title: The OpenTracing project
baseURL: /
languageCode: en-us
enableRobotsTXT: true
theme: tracer

taxonomies:
  tag: tags
  category: categories

params:
  description: Consistent, expressive, vendor-neutral APIs for distributed tracing and context propagation
