title: The OpenTracing project
baseURL: /
languageCode: en-us
enableRobotsTXT: true

taxonomies:
  tag: tags
  category: categories

params:
  description: Consistent, expressive, vendor-neutral APIs for distributed tracing and context propagation
  hero:
    tagline: Vendor-neutral APIs and instrumentation for distributed tracing
    update:
      title: "February 2018: OpenTracing Project Update"
      url: https://medium.com/opentracing/february-2018-opentracing-monthly-newsletter-7700560e9b04
  companies:
  - name: Uber
    url: https://eng.uber.com
    icon: /img/companies/uber.png
  - name: Apple
    url: https://apple.com
    icon: https://simpleicons.org/icons/apple.svg
  - name: Yelp
    url: https://yelp.com
    icon: https://upload.wikimedia.org/wikipedia/commons/a/ad/Yelp_Logo.svg
  - name: Pinterest
    url: https://pinterest.com
    icon: /img/companies/pinterest.png
  - name: Workiva
    url: https://workiva.com
    icon: https://upload.wikimedia.org/wikipedia/commons/1/19/Workiva-Logo-Digital_and_Web.png
  - name: Joyent
    url: https://www.joyent.com
    icon: /img/companies/joyent.png
  - name: Cockroach Labs
    url: https://www.cockroachlabs.com
    icon: /img/companies/cockroach.png
  - name: Sourcegraph
    url: https://sourcegraph.com/
    icon: /img/companies/sourcegraph.png
  - name: Stream
    url: https://getstream.io/
    icon: /img/companies/stream.png
  tracers:
  - name: Zipkin
    url: http://zipkin.io
    icon: /img/tracers/zipkin_small.png
  - name: Lightstep
    url: http://lightstep.com
    icon: /img/tracers/lightstep.png
  - name: Appdash
    url: https://github.com/sourcegraph/appdash
    icon: /img/tracers/appdash.png
  - name: Tracer
    url: https://github.com/tracer/tracer
    icon: false
  - name: Jaeger
    url: http://uber.github.io/jaeger/
    icon: false
  - name: Hawkular
    url: http://www.hawkular.org/hawkular-apm/
    icon: /img/tracers/hawkular.svg
  - name: Instana
    url: https://www.instana.com
    icon: /img/tracers/instana.svg
  - name: Skywalking
    url: http://skywalking.org
    icon: /img/tracers/skywalking.png
  - name: inspectIT
    url: http://www.inspectit.rocks
    icon: /img/tracers/inspectit.png
  - name: stagemonitor
    url: http://www.stagemonitor.org/
    icon: /img/tracers/stagemonitor.png
  - name: datadog
    url: https://www.datadoghq.com/
    icon: /img/tracers/datadog.png
  frameworks:
  - name: gRPC
    url: http://grpc.io
    icon: img/frameworks/grpc.svg
  - name: Flask
    url: http://flask.pocoo.org/
    icon: img/frameworks/flask.svg
  - name: go-kit
    url: https://gokit.io/
    icon: img/frameworks/gokit.png
  - name: Django
    url: https://www.djangoproject.com
    icon: img/frameworks/django.svg
  - name: Dropwizard
    url: http://www.dropwizard.io/
    icon: false
  - name: Motan
    url: https://github.com/weibocom/motan
    icon: false
  - name: Hprose
    url: http://hprose.com
    icon: img/frameworks/hprose.svg
  - name: ShardingJDBC
    url: https://github.com/shardingjdbc/sharding-jdbc
    icon: img/frameworks/sharding_jdbc.png
  social:
  - name: Medium
    url:  //medium.com/opentracing
    icon: img/social/medium.png
  - name: Github
    url:  //github.com/opentracing
    icon: img/social/github.png
  - name: Twitter
    url:  //twitter.com/opentracing
    icon: img/social/twitter.png
  - name: Gitter
    url:  //gitter.im/opentracing/public
    icon: img/social/gitter.png
